name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.0
  sqflite_common_ffi: ^2.3.1
  io: ^1.0.4
  path_provider: ^2.1.1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
